### ISSUE TITLE
Integrating Relay Modern

### ISSUE THREAD

**Issue by leebenson** [leebenson/reactql-docs#7]
Show how Apollo could be swapped out for Relay, and what the potential pros/cons are.

**Comment by Extra-lightwill** [comment]
Have you had time to make any progress on this?

**Comment by leebenson** [comment]
Not yet. I'm heavily invested in Apollo in production, and I've not had the time to explore Relay Modern and swapping it in. Realistically, it'll be a few weeks until I can get to this. I'm open to PRs in the meantime, especially to the [examples](https://github.com/reactql/examples) repo.

I'll also move this to [new docs](https://github.com/reactql/docs) to track.

**Comment by leebenson** [comment]
tracked [here](https://github.com/reactql/examples/issues/1)
